### ISSUE TITLE
HRSC2016 dataset to GGHL format 

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/GGHL#15]
Hello sir, 
please can you tell me in which format should i convert HRSC2016 dataset , need i to convert it to DOTA format or VOC format because DOTA2Train.py  require labelTxt folder which is DOTA format and evaluatorGGHL.py require VOC format , can you please explain me the steps to prepare HRSC2016 dataset?

**Comment by Shank2358** [comment]
> Hello sir, please can you tell me in which format should i convert HRSC2016 dataset , need i to convert it to DOTA format or VOC format because DOTA2Train.py require labelTxt folder which is DOTA format and evaluatorGGHL.py require VOC format , can you please explain me the steps to prepare HRSC2016 dataset?

Hi, the format of the data is as follows. The .xml file of HRSC2016 needs to be converted into the following format.
![image](https://user-images.githubusercontent.com/33946139/181826224-1a067ca2-e90e-49c1-bc47-aa752a21b3fd.png)

I gave the download link of the transformed dataset in another answer.

Sorry for the late reply because I was on vacation recently.

Thank you.

**Comment by TerrafYassin** [comment]
Thank you sir .
