### ISSUE TITLE
Error in validation data on HRSC2016 dataset

### ISSUE THREAD

**Issue by Ismaildata** [Shank2358/GGHL#17]

**Comment by Ismaildata** [comment]
![image](https://user-images.githubusercontent.com/109387936/182047486-0e6a6d11-a7e0-40c3-886c-5a868de995c4.png)

**Comment by Shank2358** [comment]
> ![image](https://user-images.githubusercontent.com/109387936/182047486-0e6a6d11-a7e0-40c3-886c-5a868de995c4.png)

Sorry, the problem is here. Delete line 65 of the second picture evaluatorGGHL_new.py and change it back to line 66. I also updated this code. Thanks.
![image](https://user-images.githubusercontent.com/33946139/182287875-8ebcbf86-1c8e-44ae-b9e4-0f31b3f24fb8.png)
![image](https://user-images.githubusercontent.com/33946139/182288340-5d65be1a-3470-4e42-9a08-3d1159e6cf1f.png)

**Comment by TerrafYassin** [comment]
Done , it works but receive problem  introduced on #19.
thank you.
